apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: test
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: test
            image: aoepeople/kube-container-exec:1.0
            args:
            - uptime
            env:
            - name: FILTER
              value: app=akeneo
            - name: CONTAINER
              value: akeneo
