apiVersion: batch/v1
kind: Job
metadata:
  name: test
spec:
  template:
    metadata:
      name: test
    spec:
      restartPolicy: Never
      containers:
      - name: test
        image: aoepeople/kube-container-exec:1.0
        args:
        - uptime
        env:
        - name: FILTER
          value: app=akeneo
        - name: CONTAINER
          value: akeneo
